
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module gba_rev0_sim(

	//////////// Audio //////////
	input 		          		AUD_ADCDAT,
	inout 		          		AUD_ADCLRCK,
	inout 		          		AUD_BCLK,
	output		          		AUD_DACDAT,
	inout 		          		AUD_DACLRCK,
	output		          		AUD_XCK,

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		          		DRAM_LDQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_UDQM,
	output		          		DRAM_WE_N,

	//////////// I2C for Audio and Video-In //////////
	output		          		FPGA_I2C_SCLK,
	inout 		          		FPGA_I2C_SDAT,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS,

	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO_0,

	//////////// GPIO_1, GPIO_1 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO_1
);

//parameter INIT_FILE  = "instrucoes.mif";
//parameter INIT_FILE  = "arm7tdmi_thumb_test.mif";
//parameter INIT_FILE  = "interrupt_test.mif";
parameter INIT_FILE  = "bus_test.mif";

//=======================================================
//  REG/WIRE declarations
//=======================================================

wire clock_cpu;
wire clock_sdram;
wire clock_sdram_d;
wire pll_lock;
reg test_clk = 0;

//wire clock = test_clk;
//wire clock_n = !test_clk;
wire clock;
wire clock_n;
assign clock = CLOCK_50;
assign clock_n = !CLOCK_50;
assign clock_sdram = CLOCK_50;
assign clock_sdram_d = CLOCK_50;

wire nrst;

wire tap_en;

wire [31:0] r [0:15];

wire [31:0] addr_bus;
wire [31:0] addr_cpu;
wire [31:0] addr_src_dma0, addr_dst_dma0;

wire nRW;
wire nRW_CPU;
wire [1:0] MAS;
wire [1:0] MAS_cpu;
wire [1:0] MAS_dma0;
wire MAS_16 = MAS[1] || MAS[0];

wire sign_extend;

wire [31:0] data_bus;
wire [31:0] data_bios;
wire [31:0] data_ewram;
wire [31:0] data_iwram;
wire [31:0] data_ioram;
wire [31:0] data_palram;
wire [31:0] data_vram;
wire [31:0] data_oam;
wire [31:0] data_pakrom;
wire [31:0] data_cartram;
wire [31:0] data_main;
wire [31:0] data_cpu;
wire [31:0] data_dma0;

wire        rden_bios;
wire        rden_ewram;
wire        rden_iwram;
wire        rden_palram;
wire        rden_vram;
wire        rden_oam;
wire        rden_pakrom;
wire        rden_cartram;

wire		we_ewram;
wire		we_iwram;
wire		we_ioram;
wire		we_palram;
wire		we_vram;
wire		we_oam;
wire		we_pakrom; // Used to load Game ROM
wire		we_cartram;

wire        wr_en_dma0;

// DMA0 control registers (io_registers -> dma)
wire [31:0]	dma0sad_o;
wire [31:0]	dma0dad_o;
wire [15:0]	dma0cnt_l_o;
wire [15:0]	dma0cnt_h_o;

wire [3:0]  dma_active;
assign dma_active[3:1] = 3'b0;

wire busy;
reg nWAIT = 0;
always @(negedge clock) begin
    nWAIT <= (dma_active == 0 && !busy) ? 1'b1 : 1'b0;
end
//=======================================================
//  Structural coding
//=======================================================

arm7tdmi_top arm7tdmi_top(
	.MCLK		(clock),
	.reset_n	(nrst),

	.nWAIT	(nWAIT),

	.DIN	(data_bus),
	.A		(addr_cpu),
	.DOUT	(data_cpu),
	.nRW	(nRW_CPU),
	.MAS	(MAS_cpu),
	.nMREQ	(),
	.SEQ	(),
	.nOPC	(),
	.nTRANS	(),

	.nENOUT	(),

	.sign_f	(sign_extend),

	.nIRQ	(KEY[1]),
	.nFIQ	(KEY[2]),
	.ABORT	(KEY[3]),

	.tbit_out (),

	.r0     (r[4'd0]),
    .r1     (r[4'd1]),
    .r2     (r[4'd2]),
    .r3     (r[4'd3]),
    .r4     (r[4'd4]),
    .r5     (r[4'd5]),
    .r6     (r[4'd6]),
    .r7     (r[4'd7]),
    .r8     (r[4'd8]),
    .r9     (r[4'd9]),
    .r10    (r[4'd10]),
    .r11    (r[4'd11]),
    .r12    (r[4'd12]),
    .r13    (r[4'd13]),
    .r14    (r[4'd14]),
    .r15    (r[4'd15])
);

bus_controller bus_controller(
	// input
	.rd_addr	(addr_bus),
	.nRW 	 	(nRW),

	.data_bios   (data_bios),
	.data_ewram  (data_ewram),
	.data_iwram	 (data_iwram),
	.data_ioram	 (data_ioram),
	.data_palram (data_palram),
	.data_vram	 (data_vram),
	.data_oam	 (data_oam),
	.data_pakrom (data_pakrom),
	.data_cartram(data_cartram),
	.data_main	 (data_main),

	// output
	.data_o		(data_bus),

	.rden_bios		(rden_bios),
	.rden_ewram		(rden_ewram),
	.rden_iwram		(rden_iwram),
	.rden_palram	(rden_palram),
	.rden_vram		(rden_vram),
	.rden_oam		(rden_oam),
	.rden_pakrom	(rden_pakrom),
	.rden_cartram	(rden_cartram),

	.we_ewram	(we_ewram),
	.we_iwram	(we_iwram),
	.we_ioram	(we_ioram),
	.we_palram	(we_palram),
	.we_vram	(we_vram),
	.we_oam		(we_oam),
	.we_pakrom	(we_pakrom),
	.we_cartram	(we_cartram)
);

bus_arbiter bus_arbiter (
    .addr_cpu      (addr_cpu),
    .addr_src_dma0 (addr_src_dma0), .addr_dst_dma0 (addr_dst_dma0),
    .addr_src_dma1 (), .addr_dst_dma1 (),
    .addr_src_dma2 (), .addr_dst_dma2 (),
    .addr_src_dma3 (), .addr_dst_dma3 (),

    .data_cpu      (data_cpu),
    .data_dma0     (data_dma0),
    .data_dma1     (),
    .data_dma2     (),
    .data_dma3     (),

    .MAS_cpu       (MAS_cpu),
    .MAS_dma0      (MAS_dma0),
    .MAS_dma1      (),
    .MAS_dma2      (),
    .MAS_dma3      (),

    .nRW_CPU       (nRW_CPU),
    .wr_en_dma     (wr_en_dma0),
    .dma_active    (dma_active),

    .addr_o        (addr_bus),
    .data_o        (data_main),
    .MAS           (MAS),
    .nRW           (nRW)
);

sdram_controller_top sdram_controller(
    .clock      (clock_n),
    .clock_sdram(clock_sdram),
    .nrst       (nrst),

    .rd_en      (rden_pakrom),
    .wr_en      (we_pakrom),
    .MAS        (MAS),
    .sign_extend(sign_extend),
	
    .addr       (addr_bus),
    .wr_data    (data_bus),
    .rd_data    (data_pakrom),
    .busy       (busy),
    
    .SA         (DRAM_ADDR),
    .BA         (DRAM_BA),
    .CS_N       (DRAM_CS_N),
    .CKE        (DRAM_CKE),
    .RAS_N      (DRAM_RAS_N),
    .CAS_N      (DRAM_CAS_N),
    .WE_N       (DRAM_WE_N),
    .DQ         (DRAM_DQ),
    .DQM        ({DRAM_UDQM,DRAM_LDQM})
);

assign DRAM_CLK = clock_sdram_d;

// BIOS ROM - 32bit
bios #(
    .INIT_FILE (INIT_FILE)
) bios (
    .clk	(clock_n),
    .addr	(addr_bus[13:2]),        // word address (4096 32-bit words = 16 KB)
    .rdata	(data_bios),
    .rden	(rden_bios)
);

// External Work RAM - 16bit
ewram ewram (
    .clk	(clock_n),
    .addr	(addr_bus),           // 256 KB byte address
    .wdata	(data_bus),
    .rdata	(data_ewram),
    .we		(we_ewram),
    .rden	(rden_ewram),
    .size	(MAS_16),           // 0=byte, 1=halfword
    .sign_extend (sign_extend),
    .ready	(),
    .misalign_fault	()
);

// Internal Work RAM - 32bit
iwram iwram (
    .clk	(clock_n),
    .addr	(addr_bus),           // 32 KB byte address
    .wdata	(data_bus),
    .rdata	(data_iwram),
    .we		(we_iwram),
    .rden	(rden_iwram),
    .size	(MAS),           // 00=byte 01=half 10=word
    .sign_extend (sign_extend),
    .ready	(),
    .misalign_fault	()
);

// Palette RAM - 16bit
palette_ram palette_ram (
    .clk	(clock_n),
    .addr	(addr_bus),           // 1 KB byte address
    .wdata	(data_bus),
    .rdata	(data_palram),
    .we		(we_palram),
    .rden	(rden_palram),
    .size	(MAS_16),           // 0=byte, 1=halfword
    .sign_extend (sign_extend),
    .ready	(),
    .misalign_fault	()
);

// Video RAM - 16 bit
vram vram (
    .clk	(clock_n),
    .addr	(addr_bus),           // 128 KB byte address
    .wdata	(data_bus),
    .rdata	(data_vram),
    .we		(we_vram),
    .rden	(rden_vram),
    .size	(MAS_16),           // 0=byte, 1=halfword
    .sign_extend (sign_extend),
    .ready	(),
    .misalign_fault	()
);

// Objet Atribute Memory - 32bit
oam oam (
    .clk	(clock_n),
    .addr	(addr_bus),            // 1 KB byte address
    .wdata	(data_bus),
    .rdata	(data_oam),
    .we		(we_oam),
    .rden	(rden_oam),
    .size	(MAS),
    .sign_extend (sign_extend),
    .ready	(),
    .misalign_fault	()
);

// Game PAK RAM - 8bit
cart_ram cart_ram (
    .clk	(clock_n),
    .addr	(addr_bus),     // byte address
    .wdata	(data_bus),
    .rdata	(data_cartram),
    .we		(we_cartram),
    .rden	(rden_cartram)
);

io_registers io_registers (
    .clk	(clock_n),
    .reset_n	(nrst),
    //---------------- CPU bus ----------------
    .addr	(addr_bus[9:0]),       // byte address within 1 KB IO space
    .wdata	(data_bus),
    .rdata	(data_ioram),
    .we		(we_ioram),
    .size	(MAS),             // 00=byte 01=half 10=word
    .sign_extend (sign_extend),
    .ready	(),
    .misalign_fault	(),
    //---------------- Hardware-driven read fields ----------------
    //  No PPU/keypad/serial hardware wired yet — tie to idle defaults.
    .vcount_i	(16'd0),       // REG_VCOUNT (only low 8 bits meaningful)
    .vblank_status_i (1'b0),   // DISPSTAT bit 0 (W)
    .hblank_status_i (1'b0),   // DISPSTAT bit 1 (G)
    .vcount_match_i  (1'b0),   // DISPSTAT bit 2 (Z)
    .keypad_i	(16'h03FF),    // REG_KEY (active low) — all keys released
    .irq_request_i (14'd0),    // pulses set the IF bits
    .sound_status_i (4'd0),    // SOUNDCNT_X bits 0-3
    .serial_data0_i (16'd0),   // SCD0 (received)
    .serial_data1_i (16'd0),   // SCD1
    .serial_data2_i (16'd0),   // SCD2
    .serial_data3_i (16'd0),   // SCD3
    //---------------- Direct Sound FIFO write strobes ----------------
    //  No sound DMA path wired yet — leave outputs open.
    .fifo_a_we_o	(),
    .fifo_b_we_o	(),
    .fifo_a_byteena_o (),
    .fifo_b_byteena_o (),
    .fifo_a_data_o	(),
    .fifo_b_data_o	(),
    //---------------- Display ----------------
    .dispcnt_o	(),
    .dispstat_o	(),
    //---------------- Backgrounds ----------------
    .bg0cnt_o (), .bg1cnt_o (), .bg2cnt_o (), .bg3cnt_o (),
    .bg0hofs_o (), .bg0vofs_o (),
    .bg1hofs_o (), .bg1vofs_o (),
    .bg2hofs_o (), .bg2vofs_o (),
    .bg3hofs_o (), .bg3vofs_o (),
    .bg2pa_o (), .bg2pb_o (), .bg2pc_o (), .bg2pd_o (),
    .bg3pa_o (), .bg3pb_o (), .bg3pc_o (), .bg3pd_o (),
    .bg2x_o (), .bg2y_o (),
    .bg3x_o (), .bg3y_o (),
    //---------------- Window ----------------
    .win0h_o (), .win1h_o (), .win0v_o (), .win1v_o (),
    .winin_o (), .winout_o (),
    //---------------- Effects ----------------
    .mosaic_o	(),
    .bldmod_o (), .colev_o (), .coley_o (),
    //---------------- Sound (master only — channel regs read via CPU) ----------------
    .soundcnt_l_o (), .soundcnt_h_o (), .soundcnt_x_o (), .soundbias_o (),
    //---------------- DMA ----------------
    .dma0sad_o (dma0sad_o), .dma0dad_o (dma0dad_o),
    .dma0cnt_l_o (dma0cnt_l_o), .dma0cnt_h_o (dma0cnt_h_o),
    .dma1sad_o (), .dma1dad_o (),
    .dma1cnt_l_o (), .dma1cnt_h_o (),
    .dma2sad_o (), .dma2dad_o (),
    .dma2cnt_l_o (), .dma2cnt_h_o (),
    .dma3sad_o (), .dma3dad_o (),
    .dma3cnt_l_o (), .dma3cnt_h_o (),
    //---------------- Timers ----------------
    .tm0d_o (), .tm0cnt_o (),
    .tm1d_o (), .tm1cnt_o (),
    .tm2d_o (), .tm2cnt_o (),
    .tm3d_o (), .tm3cnt_o (),
    //---------------- Serial ----------------
    .sccnt_l_o (), .sccnt_h_o (),
    //---------------- Keypad ----------------
    .p1cnt_o	(),
    //---------------- Link / JOY-bus ----------------
    .r_o		(),
    .hs_ctrl_o	(),
    .joyre_o	(),
    .joytr_o	(),
    .jstat_o	(),
    //---------------- Interrupts ----------------
    .ie_o		(),
    .if_o		(),
    .wscnt_o	(),
    .ime_o		()
);

// DMA0 channel. Single instance for now (default param targets DMA0 at 0x040000BA)
dma dma0 (
    .clock		(clock),
    .dmasad_o	(dma0sad_o),
    .dmadad_o	(dma0dad_o),
    .dmacnt_l_o (dma0cnt_l_o),
    .dmacnt_h_o (dma0cnt_h_o),
    .data_i	    (data_bus),        // no DMA read path / bus arbiter yet
    .vblank		(1'b0),         // no PPU timing wired yet
    .hblank		(1'b0),
    .halt       (busy),
    .src_addr	(addr_src_dma0),
    .dst_addr	(addr_dst_dma0),
    .data_o 	(data_dma0),
    .wr_en		(wr_en_dma0),
    .MAS		(MAS_dma0),
    .dma_active	(dma_active[0]),
    .IRQ		()
);

seg_display seg_display(
    .in({r[0][7:0], addr_bus[15:0]}),
	.clk (clock),

    .s0(HEX0),
    .s1(HEX1),
    .s2(HEX2),
    .s3(HEX3),
    .s4(HEX4),
    .s5(HEX5)
);

//pll  pll(
//	.refclk	(CLOCK_50),
////	.rst	(~nrst|| SW[0]),
//	.rst	(SW[0]),
//
//	.outclk_0(clock_cpu),
//	.outclk_1(clock_sdram),
//	.outclk_2(clock_sdram_d),
//	.locked  (pll_lock)
//);
//
//integer count = 0;
//wire startup_rst = SW[0] | ~pll_lock;
//always @(posedge clock_cpu or posedge startup_rst) begin
//	if (startup_rst) count <= 0;
//	else if (count >= 32'd249_999) count <= 0;
//	else count <= count+1;
//end
//
//always @(posedge clock_cpu or posedge startup_rst) begin
//    if (startup_rst)                 test_clk <= 1'b0;
//    else if (count == 32'd249_999)   test_clk <= ~test_clk;
//end

//clkctrl_cpu clkctrl_cpu (
//	.inclk  (test_clk),  //  altclkctrl_input.inclk
//	.outclk (clock)  // altclkctrl_output.outclk
//);

//genvar i;
//generate
//	for (i = 0;i < 16 ; i = i+1) begin: reg_taps
//		signal_tap reg_bank_tap (
//		.acq_data_in    (r[i]),    //     tap.acq_data_in
//		.acq_trigger_in (tap_en), //        .acq_trigger_in
//		.acq_clk        (clock)         // acq_clk.clk
//	);
//	end
//endgenerate
//
//signal_tap addr_tap (
//		.acq_data_in    (addr_bus),    //     tap.acq_data_in
//		.acq_trigger_in (tap_en), //        .acq_trigger_in
//		.acq_clk        (clock)         // acq_clk.clk
//);
//
//signal_tap din_tap (
//		.acq_data_in    (data_bus),    //     tap.acq_data_in
//		.acq_trigger_in (tap_en), //        .acq_trigger_in
//		.acq_clk        (clock)         // acq_clk.clk
//);

assign nrst = ~SW[1];
assign tap_en = SW[9];
assign LEDR[0] = clock;

endmodule
